GUIDE_PERSONA = {
    "name": "Guide",
    "identity_zh": "浦江国际学院（Global College）的正式专业讲解员",
    "identity_en": "A formal professional guide for Global College",
    "rules": [
        "使用当前活跃代表团来访任务中指定的语言、路线和播报脚本。",
        "不主动询问兴趣、来访目的或活动偏好；这些内容由管理者预先配置。",
        "只依据数据库返回的学院、建筑、活动和展品信息进行讲解。",
        "路线计算可保留完整节点和分段，但首次播报只说一条简短、以访客电梯为核心的指引；不得朗读内部路径节点。",
        "同楼层会议室统一播报为“会议室就在您所在的楼层，位于电梯出口附近”，不逐段播报。",
        "跨楼层优先说明目标楼层、访客电梯和出电梯后的关键转向；收到新的照片定位结果后再核对路线。",
        "进入已配置展区时可以自动讲解，离开展区后停止该展区播报。",
        "来访者提问时暂停当前播报，回答后再继续既定讲解任务。",
        "不主动泛化推荐活动；已归档活动被询问时明确说明活动已经结束。",
        "数据库没有答案时，说明资料不足并建议咨询相关办公室。",
        "拒绝涉政以及与学院无关的话题。",
        "定位、VLM、数据库或 MCP 服务不可用时停止导览并提示联系工作人员更换设备。",
        "路线只能使用后端返回的确定性路线，不自行猜测墙体、出口或通行方向。",
        "绝不推荐标记为 restricted、guest_access=false 或不可进入的电梯和区域。",
    ],
}


MCP_TOOL_CONTRACTS = [
    {
        "name": "museum.search_knowledge",
        "description": "Search permanent college/building knowledge and exhibit records.",
        "method": "GET",
        "endpoint": "/api/v1/knowledge/search",
        "parameters": ["q", "kind", "floor", "include_archived"],
    },
    {
        "name": "museum.get_place_info",
        "description": "Get records attached to a mapped region node.",
        "method": "GET",
        "endpoint": "/api/v1/knowledge/search",
        "parameters": ["node_id"],
    },
    {
        "name": "museum.search_events",
        "description": "Search active or archived exhibitions and events.",
        "method": "GET",
        "endpoint": "/api/v1/events",
        "parameters": ["q", "floor", "include_archived"],
    },
    {
        "name": "museum.get_event",
        "description": "Get one event by database record ID.",
        "method": "GET",
        "endpoint": "/api/v1/events/{record_id}",
        "parameters": ["record_id"],
    },
    {
        "name": "museum.get_nearby_events",
        "description": "Find active events on or near the current mapped node.",
        "method": "GET",
        "endpoint": "/api/v1/events/nearby",
        "parameters": ["node_id"],
    },
    {
        "name": "museum.get_visitor_context",
        "description": "Read the current active delegation visit task.",
        "method": "GET",
        "endpoint": "/api/v1/guide/context",
        "parameters": ["visit_id", "current_node"],
    },
    {
        "name": "museum.get_guide_context",
        "description": "Compose persona, visit task, and location knowledge for Guide.",
        "method": "GET",
        "endpoint": "/api/v1/guide/context",
        "parameters": ["visit_id", "current_node"],
    },
    {
        "name": "museum.search_map_nodes",
        "description": "Search SQLite floor-map nodes and calibration state.",
        "method": "GET",
        "endpoint": "/api/v1/map/nodes",
        "parameters": ["q", "floor", "kind", "routable"],
    },
    {
        "name": "museum.get_map_node",
        "description": "Get one SQLite map node by ID.",
        "method": "GET",
        "endpoint": "/api/v1/map/nodes/{node_id}",
        "parameters": ["node_id"],
    },
    {
        "name": "museum.plan_route",
        "description": "Plan a deterministic route using SQLite map nodes and edges.",
        "method": "POST",
        "endpoint": "/api/v1/route",
        "parameters": ["from_location", "to_location", "language", "accessible_only"],
    },
]
