"""Transcribe public GC audio guides and import them into guide.sqlite3.

The source pages are official public audio-guide pages. The transcript text is
generated by ASR and intentionally marked as unreviewed provenance in the DB.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote, urlsplit, urlunsplit

import httpx


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from server.app.errors import VlmNotConfiguredError, VlmResponseError
from server.app.knowledge import KnowledgeStore
from server.app.vlm import VlmClient


@dataclass(frozen=True)
class AudioGuide:
    slug: str
    source_url: str
    node_id: str
    group_code: str
    floor: int
    title_zh: str
    title_en: str
    audio_zh: str
    audio_en: str
    geometry: list[list[float]]


PUBLIC_AUDIO_GUIDES: tuple[AudioGuide, ...] = (
    AudioGuide(
        slug="audio-guide-2",
        source_url="https://gc.sjtu.edu.cn/audio-guide-2/",
        node_id="LB-1F-AUDIO-LONGBIN-COMPLETION",
        group_code="AUDIO-2",
        floor=1,
        title_zh="龙宾楼落成志（一楼）",
        title_en="Long Bin Building Completion Chronicle (Floor 1)",
        audio_zh="https://gc.sjtu.edu.cn/wp-content/uploads/2024/09/龙宾楼落成志（一楼）.mp3",
        audio_en="https://gc.sjtu.edu.cn/wp-content/uploads/2024/10/2.mp3",
        geometry=[[0.42, 0.80], [0.58, 0.80], [0.58, 0.90], [0.42, 0.90]],
    ),
    AudioGuide(
        slug="audio-guide-7",
        source_url="https://gc.sjtu.edu.cn/audio-guide-7/",
        node_id="LB-1F-AUDIO-GRATITUDE-WALL",
        group_code="AUDIO-7",
        floor=1,
        title_zh="感恩墙（一楼）",
        title_en="Gratitude Wall (Floor 1)",
        audio_zh="https://gc.sjtu.edu.cn/wp-content/uploads/2024/09/感恩墙（一楼）.mp3",
        audio_en="https://gc.sjtu.edu.cn/wp-content/uploads/2024/10/7.mp3",
        geometry=[[0.24, 0.42], [0.34, 0.42], [0.34, 0.58], [0.24, 0.58]],
    ),
    AudioGuide(
        slug="audio-guide-6",
        source_url="https://gc.sjtu.edu.cn/audio-guide-6/",
        node_id="LB-1F-AUDIO-ALUMNI-NORTH",
        group_code="AUDIO-6",
        floor=1,
        title_zh="新时代的追光者系列：学术校友展（北侧）（一楼）",
        title_en="New Era Light Chasers: Academic Alumni Exhibition, North Side (Floor 1)",
        audio_zh="https://gc.sjtu.edu.cn/wp-content/uploads/2024/09/新时代的追光者系列-学术校友展（北侧）（一楼）.mp3",
        audio_en="https://gc.sjtu.edu.cn/wp-content/uploads/2024/10/6.mp3",
        geometry=[[0.38, 0.28], [0.67, 0.28], [0.67, 0.42], [0.38, 0.42]],
    ),
    AudioGuide(
        slug="audio-guide-14",
        source_url="https://gc.sjtu.edu.cn/audio-guide-14/",
        node_id="LB-4F-AUDIO-JI-HISTORY",
        group_code="AUDIO-14",
        floor=4,
        title_zh="交大密西根学院院史（四楼）",
        title_en="History of SJTU Joint Institute (Floor 4)",
        audio_zh="https://gc.sjtu.edu.cn/wp-content/uploads/2024/09/交大密西根学院院史（四楼）.mp3",
        audio_en="https://gc.sjtu.edu.cn/wp-content/uploads/2024/10/14.mp3",
        geometry=[[0.78, 0.12], [0.93, 0.12], [0.93, 0.28], [0.78, 0.28]],
    ),
    AudioGuide(
        slug="audio-guide-12",
        source_url="https://gc.sjtu.edu.cn/audio-guide-12/",
        node_id="LB-3F-AUDIO-SJTU-UM-HISTORY",
        group_code="AUDIO-12",
        floor=3,
        title_zh="交大密大合作史：百年携手，世纪跨越（三楼）",
        title_en="SJTU-UM Cooperation History: Century-long Partnership (Floor 3)",
        audio_zh="https://gc.sjtu.edu.cn/wp-content/uploads/2024/09/交大密大合作史-百年携手世纪跨越（三楼）.mp3",
        audio_en="https://gc.sjtu.edu.cn/wp-content/uploads/2024/10/12.mp3",
        geometry=[[0.36, 0.12], [0.65, 0.12], [0.65, 0.28], [0.36, 0.28]],
    ),
    AudioGuide(
        slug="audio-guide-9",
        source_url="https://gc.sjtu.edu.cn/audio-guide-9/",
        node_id="LB-3F-AUDIO-WATERCOLOR",
        group_code="AUDIO-9",
        floor=3,
        title_zh="芳华水彩组画（三楼）",
        title_en="Fanghua Watercolor Paintings (Floor 3)",
        audio_zh="https://gc.sjtu.edu.cn/wp-content/uploads/2024/09/芳华水彩组画（三楼）.mp3",
        audio_en="https://gc.sjtu.edu.cn/wp-content/uploads/2024/10/9.mp3",
        geometry=[[0.30, 0.60], [0.45, 0.60], [0.45, 0.76], [0.30, 0.76]],
    ),
)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def url_for_json(value: str) -> str:
    parsed = urlsplit(value)
    return urlunsplit(
        (
            parsed.scheme,
            parsed.netloc,
            quote(parsed.path, safe="/%"),
            parsed.query,
            parsed.fragment,
        )
    )


class QwenAsrClient:
    def __init__(self) -> None:
        vlm = VlmClient()
        self.url = vlm.chat_completions_url
        self.api_key = vlm.api_key
        self.model = os.getenv("ASR_MODEL", "qwen3-asr-flash")
        self.timeout = float(os.getenv("ASR_TIMEOUT_SECONDS", "180"))
        if not (self.url and self.api_key and self.model):
            raise VlmNotConfiguredError(
                "请设置 VLM_BASE_URL、VLM_API_KEY，并确认 ASR_MODEL 或默认 qwen3-asr-flash 可用"
            )

    async def transcribe(self, audio_url: str) -> str:
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_audio",
                            "input_audio": {"data": url_for_json(audio_url)},
                        }
                    ],
                }
            ],
            "stream": False,
            "asr_options": {"enable_itn": False},
        }
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(self.url, headers=headers, json=payload)
                response.raise_for_status()
                body = response.json()
                content = body["choices"][0]["message"]["content"]
        except (httpx.HTTPError, ValueError, KeyError, IndexError, TypeError) as exc:
            raise VlmResponseError(f"ASR 转写失败：{exc}") from exc
        if not isinstance(content, str) or not content.strip():
            raise VlmResponseError("ASR 未返回有效文字稿")
        return content.strip()


def upsert_audio_guide(
    store: KnowledgeStore,
    guide: AudioGuide,
    transcript_zh: str,
    transcript_en: str,
    asr_model: str,
) -> dict[str, Any]:
    extracted = {
        "source_type": "public_audio_guide",
        "source_url": guide.source_url,
        "audio_urls": {"zh": guide.audio_zh, "en": guide.audio_en},
        "asr": {
            "provider": "qwen",
            "model": asr_model,
            "generated_at": now_iso(),
            "review_status": "unreviewed",
        },
        "notes": [
            "Transcript generated from official public audio-guide audio.",
            "ASR text has not been manually proofread.",
        ],
    }
    payload = {
        "node_id": guide.node_id,
        "group_code": guide.group_code,
        "floor": guide.floor,
        "geometry": guide.geometry,
        "kind": "permanent",
        "title_zh": guide.title_zh,
        "title_en": guide.title_en,
        "content_zh": transcript_zh,
        "content_en": transcript_en,
        "tags": [
            "public_audio_guide",
            "gc.sjtu.edu.cn",
            guide.slug,
            "asr_transcript",
            "unreviewed_asr",
        ],
        "source": (
            f"GC public audio guide {guide.source_url}; "
            f"zh_audio={guide.audio_zh}; en_audio={guide.audio_en}; ASR unreviewed"
        ),
        "extracted": extracted,
    }

    existing = next(
        (
            entry
            for entry in store.list_entries(include_archived=True)
            if entry["node_id"] == guide.node_id
        ),
        None,
    )
    if existing is None:
        created = store.create_entry(payload)
        return store.update_entry(created["id"], {"extracted": extracted})
    if existing["status"] == "archived":
        store.set_archived(existing["id"], False)
    return store.update_entry(existing["id"], payload)


async def import_guides(dry_run: bool) -> list[dict[str, Any]]:
    asr = QwenAsrClient()
    store = KnowledgeStore()
    imported: list[dict[str, Any]] = []
    for guide in PUBLIC_AUDIO_GUIDES:
        print(f"transcribing {guide.slug} zh")
        transcript_zh = await asr.transcribe(guide.audio_zh)
        print(f"transcribing {guide.slug} en")
        transcript_en = await asr.transcribe(guide.audio_en)
        row = {
            "node_id": guide.node_id,
            "title_zh": guide.title_zh,
            "title_en": guide.title_en,
            "zh_chars": len(transcript_zh),
            "en_chars": len(transcript_en),
        }
        if not dry_run:
            entry = upsert_audio_guide(
                store,
                guide,
                transcript_zh,
                transcript_en,
                asr.model,
            )
            row["record_id"] = entry["id"]
        imported.append(row)
        print(json.dumps(row, ensure_ascii=False))
    return imported


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Transcribe and print metadata without updating guide.sqlite3.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    imported = asyncio.run(import_guides(args.dry_run))
    print(json.dumps({"imported": imported}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
